const express = require("express");
const router = express.Router();
const { authentication } = require("../middleware/authentication");
const userController = require("../controllers/usersControl");
router.get("/products", authentication, userController.getProducts);
router.get("/products/:id", authentication, userController.productsById);
router.get("/product", userController.productByCategory);
router.get("/:id/cart", authentication, userController.getCart);
router.post("/login", userController.login);
router.post("/register", userController.register);
router.post("/:id/cart", authentication, userController.cartByIdPost);
router.get("/:id/wishlist", authentication, userController.wishlist);
router.delete("/:id/wishlist", authentication, userController.deleteWishlist);
module.exports = router;
